import { h } from "@stencil/core";
export class Colors {
    render() {
        return [
            h("div", { class: "container max-width-md padding-y-md" },
                h("div", { class: "theme", "data-theme": 'beko' },
                    h("h5", { class: "padding-sm" }, "Beko"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-primary-lighter" }),
                        h("div", { class: "col square bg-primary-light" }),
                        h("div", { class: "col square bg-primary" }),
                        h("div", { class: "col square bg-primary-dark" }),
                        h("div", { class: "col square bg-primary-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-lighter"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-light"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary: #0083BE"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-dark"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-darker"))),
                h("div", { class: "theme", "data-theme": 'hoover' },
                    h("h5", { class: "padding-sm" }, "Hoover"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-primary-lighter" }),
                        h("div", { class: "col square bg-primary-light" }),
                        h("div", { class: "col square bg-primary" }),
                        h("div", { class: "col square bg-primary-dark" }),
                        h("div", { class: "col square bg-primary-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-lighter"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-light"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary: #DD052b"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-dark"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-darker"))),
                h("div", { class: "theme", "data-theme": 'candy' },
                    h("h5", { class: "padding-sm" }, "Candy"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-primary-lighter" }),
                        h("div", { class: "col square bg-primary-light" }),
                        h("div", { class: "col square bg-primary" }),
                        h("div", { class: "col square bg-primary-dark" }),
                        h("div", { class: "col square bg-primary-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-lighter"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-light"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary: #00AEE6"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-dark"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-darker"))),
                h("div", { class: "theme", "data-theme": 'hotpoint' },
                    h("h5", { class: "padding-sm" }, "Hotpoint"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-primary-lighter" }),
                        h("div", { class: "col square bg-primary-light" }),
                        h("div", { class: "col square bg-primary" }),
                        h("div", { class: "col square bg-primary-dark" }),
                        h("div", { class: "col square bg-primary-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-lighter"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-light"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary: #1FB5BE"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-dark"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-primary-darker"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Color Success"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-success-lighter" }),
                        h("div", { class: "col square bg-success-light" }),
                        h("div", { class: "col square bg-success" }),
                        h("div", { class: "col square bg-success-dark" }),
                        h("div", { class: "col square bg-success-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-success-lower"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-success-low"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-success-medium"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-success-high"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-success-higher"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Color Error"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-error-lighter" }),
                        h("div", { class: "col square bg-error-light" }),
                        h("div", { class: "col square bg-error" }),
                        h("div", { class: "col square bg-error-dark" }),
                        h("div", { class: "col square bg-error-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-error-lower"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-error-low"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-error-medium"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-error-high"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-error-higher"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Color Warning"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-warning-lighter" }),
                        h("div", { class: "col square bg-warning-light" }),
                        h("div", { class: "col square bg-warning" }),
                        h("div", { class: "col square bg-warning-dark" }),
                        h("div", { class: "col square bg-warning-darker" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-warning-lower"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-warning-low"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-warning-medium"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-warning-high"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-warning-higher"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Contrast Scale"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg" }),
                        h("div", { class: "col square bg-contrast-lower" }),
                        h("div", { class: "col square bg-contrast-low" }),
                        h("div", { class: "col square bg-contrast-medium" }),
                        h("div", { class: "col square bg-contrast-high" }),
                        h("div", { class: "col square bg-contrast-higher" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-bg"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-contrast-lower"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-contrast-low"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-contrast-medium"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-contrast-high"),
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--color-contrast-higher"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Color Black"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-black" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--bg-black"))),
                h("div", { class: "theme" },
                    h("h5", { class: "padding-sm" }, "Color White"),
                    h("div", { class: "grid margin-top" },
                        h("div", { class: "col square bg-white border border-contrast-low border-2" })),
                    h("div", { class: "grid" },
                        h("div", { class: "col text-xs text-center padding-top-sm" }, "--bg-white"))))
        ];
    }
    static get is() { return "frp-colors"; }
    static get encapsulation() { return "shadow"; }
    static get originalStyleUrls() { return {
        "$": ["./colors.scss"]
    }; }
    static get styleUrls() { return {
        "$": ["colors.css"]
    }; }
}
